WeddingRestaurant/WeddingRestaurant/Models/Menu.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WeddingRestaurant.Models
{
    public class Menu
    {
        [Key]
        public int Id{ get; set; }
        [Required]
        [StringLength(50)]
        public string Name{ get; set; }
        [ForeignKey("TypeMenu")]
        public int TypeID { get; set; }
        public virtual TypeMenu? TypeMenu { get; set; }
        //public ICollection<Product>? Products { get; set; }
    }
}

WeddingRestaurant/WeddingRestaurant/Areas/Admin/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WeddingRestaurant.Heplers;
using WeddingRestaurant.Interfaces;
using WeddingRestaurant.Models;
using WeddingRestaurant.Repositories;

namespace WeddingRestaurant.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = Configuration.RoleAdmin)]
    public class MenusController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public MenusController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Admin/Menus
        public async Task<IActionResult> Index(int page = 1)
        {
            int pageSize = 12;
            var pagedList = await _unitOfWork.Menus.GetAllMenus(page, pageSize);
            return View(pagedList);

        }
        // GET: Admin/Menus/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _unitOfWork.Menus.GetMenuById(id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // GET: Admin/Menus/Create
        public async Task<IActionResult> Create()
        {
            ViewData["TypeID"] = new SelectList(await _unitOfWork.TypeMenus.GetAllAsync(), "Id", "Name");
            return View();
        }

        // POST: Admin/Menus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,TypeID")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                string menuName = menu.Name.Trim();
                if (await MenuExistsByName(menuName))
                {
                    TempData["MenuExists"] = "Tên Menu đã tồn tại";
                    ViewData["TypeID"] = new SelectList(await _unitOfWork.TypeMenus.GetAllAsync(), "Id", "Name");

                    return View(menu);
                }
                await _unitOfWork.Menus.AddAsync(menu);
                await _unitOfWork.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            ViewData["TypeID"] = new SelectList(await _unitOfWork.TypeMenus.GetAllAsync(), "Id", "Name");
            return View(menu);
        }

        // GET: Admin/Menus/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _unitOfWork.Menus.GetMenuById(id);
            if (menu == null)
            {
                return NotFound();
            }
            ViewData["TypeID"] = new SelectList(await _unitOfWork.TypeMenus.GetAllAsync(), "Id", "Name");
            return View(menu);
        }

        // POST: Admin/Menus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,TypeID")] Menu menu)
        {
            if (id != menu.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                var existingMenu = await _unitOfWork.Menus.GetByIdAsync(id);
                string menuName = menu.Name.Trim();
                if (!existingMenu.Name.Equals(menuName))
                {
                    if (await MenuExistsByName(menuName))
                    {
                        TempData["MenuExists"] = "Món ăn đã tồn tại";
                        ViewData["TypeID"] = new SelectList(await _unitOfWork.TypeMenus.GetAllAsync(), "Id", "Name");

                        return View(menu);
                    }
                }

                existingMenu.Name = menu.Name;
                existingMenu.TypeID = menu.TypeID;

                //await _unitOfWork.Menus.UpdateAsync(menu);
                await _unitOfWork.SaveChangesAsync();
                
                return RedirectToAction(nameof(Index));
            }
            ViewData["TypeID"] = new SelectList(await _unitOfWork.TypeMenus.GetAllAsync(), "Id", "Name");
            return View(menu);
        }

        // GET: Admin/Menus/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _unitOfWork.Menus.GetMenuById(id);

            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // POST: Admin/Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await _unitOfWork.Menus.DeleteAsync(id);
            await _unitOfWork.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> MenuExistsByName(string name)
        {
            return await _unitOfWork.Menus.GetMenuByName(name);
        }
    }
}

WeddingRestaurant/WeddingRestaurant/Areas/Customers/Controllers/MenuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WeddingRestaurant.Heplers;
using WeddingRestaurant.Interfaces;
using WeddingRestaurant.Models;
using WeddingRestaurant.Repositories;
using WeddingRestaurant.ViewModels;

namespace WeddingRestaurant.Areas.Customers.Controllers
{
    [Area("Customers")]
    public class MenuController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public MenuController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index(int? id)
        {
            var cart = HttpContext.Session.Get<List<CartItem>>(Configuration.CART_KEY) ?? new List<CartItem>();

            List<int> productIdsInCart = cart.Select(item => item.Id).ToList();
            var menus = await _unitOfWork.Menus.GetMenuByTypeMenuId(id, productIdsInCart);

            return View(menus);
        }

    }
}

WeddingRestaurant/WeddingRestaurant/Areas/Admin/Views/Menus/Create.cshtml
@model WeddingRestaurant.Models.Menu

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Menu</h4>

@if (TempData["MenuExists"] != null)
{
    <h4 style="color: #dc3545;
    padding: 5px;">
        @TempData["MenuExists"]
    </h4>
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeID" class="control-label"></label>
                <select asp-for="TypeID" class ="form-control" asp-items="ViewBag.TypeID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WeddingRestaurant/WeddingRestaurant/Areas/Admin/Views/Menus/Delete.cshtml
@model WeddingRestaurant.Models.Menu

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Menu</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeMenu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeMenu.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WeddingRestaurant/WeddingRestaurant/Areas/Admin/Views/Menus/Details.cshtml
@model WeddingRestaurant.Models.Menu

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Menu</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeMenu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeMenu.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WeddingRestaurant/WeddingRestaurant/Areas/Admin/Views/Menus/Edit.cshtml
@model WeddingRestaurant.Models.Menu

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Menu</h4>

@if (TempData["MenuExists"] != null)
{
    <h4 style="color: #dc3545;
    padding: 5px;">
        @TempData["MenuExists"]
    </h4>
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeID" class="control-label"></label>
                <select asp-for="TypeID" class="form-control" asp-items="ViewBag.TypeID"></select>
                <span asp-validation-for="TypeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WeddingRestaurant/WeddingRestaurant/Areas/Admin/Views/Menus/Index.cshtml
@* @model IEnumerable<WeddingRestaurant.Models.Menu> *@
@model X.PagedList.IPagedList<WeddingRestaurant.Models.Menu>
@using X.PagedList.Mvc.Core
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                TypeMenu
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypeMenu.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
        <div class="d-flex justify-content-center">
            @Html.PagedListPager(Model, page => Url.Action("Index", "Menus", new { page = page }))
        </div>
    </tbody>
</table>